### ISSUE TITLE
MTA Api

### ISSUE THREAD

**Issue by itajenglish** [noahfeder/train_status#1]
I'm having trouble finding the api you guys used to get the train data?

**Comment by noahfeder** [comment]
We used a version of [John Bell's Sinatra API](https://github.com/johnrbell/mta_api). 

I wrapped his methods into an additional backend in Rails that I cleaned up post-hackathon [here](https://github.com/noahfeder/train_backend)

**Comment by itajenglish** [comment]
Ahh I see nice! http://mta.millenialsears.com/trains is this the api you guys created?

**Comment by noahfeder** [comment]
Correct! That's where I deployed a Rails server based on John's Sinatra code
